baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "superchig"
theme = 'matklad-like'

[author]
  name = 'Christopher Chang'

# Modify to show about (no resume)
[menu]
  # [[menu.main]]
  #   name = "Home"
  #   pre = "home"
  #   url = "/"
  #   weight = 1
  [[menu.main]]
    name = "About"
    # pre = "pen-tool"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3

[params]
  dateFormat = "Jan 2, 2006"
  githubLink = 'https://github.com/Superchig'
  githubUsername = 'Superchig'

# [permalinks]
#   posts = "/:title" 

